version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: event_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=sqlite+aiosqlite:///data/bot.db
    volumes:
      - ./data:/app/data
    env_file:
      - .env